title: Ayan Gaur
logo: assets/img/IMG_0180.jpg
description: >
  Senior at UC San Diego majoring in Mathematics & Computer Science
  <br>
  <br>
  <b>Email: ayan.gaur@gmail.com</b>
  <br>
  <a href=/projects/projects><b><h2>Projects</a>
  <br>
  <br>
  <a href=/experience/experience>Experience</a>
  <br>
  <br>
  <a href="https://drive.google.com/file/d/19vWw6jYu-tEbO7OvGLEYIbppEEFvLhzU/view?usp=sharing">Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/ayan-gaur/">LinkedIn</a>
  <br>
  <br>
  <a href="https://github.com/ayangaur26">GitHub</a>
  </h2></b>
  
github: false
remote_theme: pages-themes/minimal@v0.2.0
