title: Ayan Gaur
logo: assets/img/IMG_0180.jpg
description: >
  UIUC MCS - Graduating December 2026
  <br>
  <br>
  <b>Email: ayan.gaur@gmail.com</b>
  <br>
  <a href=/projects/projects><h2>Projects</a>
  <br>
  <br>
  <a href=/experience/experience>Experience</a>
  <br>
  <br>
  <a href="https://drive.google.com/file/d/1wVluPbsQZWoY1JFZFdsrDNdf-EF8gNrN/view?usp=sharing">Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/ayan-gaur/">LinkedIn</a>
  <br>
  <br>
  <a href="https://github.com/ayangaur26">GitHub</a>
  </h2>
  
github: false
remote_theme: pages-themes/minimal@v0.2.0
